package com.ssw.dao;

import com.ssw.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);
    //根据用户id和商品id查询购物车信息
    Cart findCartByuserIdAndProductId(@Param("userid") Integer userId,@Param("productid") Integer productId);
    //根据用户id查询这个用户的购物车信息
    List<Cart> findCartsByUserid(@Param("userid") Integer userid);
    //统计用户购物车中未选中的商品的数量
    Integer isAllChecked(@Param("userid") Integer userid);
    //根据用户id查看用户勾选的商品
    List<Cart> findCartsByUseridAndChecked(@Param("userId") Integer userId);
    //清空购物车中已支付的商品
    Integer cleanCart(@Param("cartList") List<Cart> cartList);

}