server:
  port: 8080
  servlet:
    context-path: /
limit:
  minMoney: 1
  maxMoney: 10
  desc: 最低${limit.minMoney}最高${limit.maxMoney}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://121.36.11.232:3306/shopping
      username: ssw
      password: 'Wei501913133.'
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  thymeleaf:
    mode: HTML
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: file:D:/upload
mybatis:
  mapper-locations: classpath*:com/ssw/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


business:
  imageHost: http://121.36.11.232/img/

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.geng.dao: debug